### ISSUE TITLE
Compile and update lambda function without AWS Gateway integration

### ISSUE THREAD

**Issue by bwbaugh** [abailly/aws-lambda-haskell#1]
It would be nice if the AWS Gateway integration was optional.

One use case for a lambda function without needing AWS Gateway in front of it is for [Amazon Alexa](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit) skills. There are probably many other use cases where we wouldn't want to expose the lambda function via an API.

**Comment by abailly** [comment]
Thanks a lot for the interest. Yes, that's definitely something I want to do: make the launcher more flexible and allow to chose which part of the process to run.
