### ISSUE TITLE
Missing git commit when `stack build`-ing

### ISSUE THREAD

**Issue by emhoracek** [abailly/aws-lambda-haskell#4]
Hi, excited to try this out, but when I did `stack build` I got this error:

```
Did not find .cabal file for websockets-0.9.6.2 with Git SHA of eaf88a1447822b483a85288f017fb1d9ef9171a0
Right Nothing
No .cabal file found in directory /Users/libby/dev/aws-lambda-haskell/system-extra/
```

**Comment by emhoracek** [comment]
Oh, you're using submodules. Could you (or I'd be happy to submit a pull request) add in the README that users should `git submodule init && git submodule update`?

**Comment by abailly** [comment]
You should sync and pull the submodules source code. I am Afk right now so
don't remember the exact commands but git help submodules should give you
enough info to proceed.

**Comment by abailly** [comment]
Did not saw your second mail. PR welcome of course. I think this can be
done automatically with stack
